#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalGraph
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="fantasyleague")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::FinalGraph.Properties.Settings.Default.fantasyleagueConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Temp_Table_of_Player_Stat> Temp_Table_of_Player_Stats
		{
			get
			{
				return this.GetTable<Temp_Table_of_Player_Stat>();
			}
		}
		
		public System.Data.Linq.Table<Player_Stat> Player_Stats
		{
			get
			{
				return this.GetTable<Player_Stat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Temp Table of Player Stats]")]
	public partial class Temp_Table_of_Player_Stat
	{
		
		private string _NBA_Stats;
		
		private string _F2;
		
		private string _F3;
		
		private string _F4;
		
		private System.Nullable<double> _F5;
		
		private System.Nullable<double> _F6;
		
		private System.Nullable<double> _F7;
		
		private System.Nullable<double> _F8;
		
		private System.Nullable<double> _F9;
		
		private System.Nullable<double> _F10;
		
		private System.Nullable<double> _F11;
		
		private System.Nullable<double> _F12;
		
		private System.Nullable<double> _F13;
		
		private System.Nullable<double> _F14;
		
		private System.Nullable<double> _F15;
		
		private System.Nullable<double> _F16;
		
		private System.Nullable<double> _F17;
		
		private System.Nullable<double> _F18;
		
		private System.Nullable<double> _F19;
		
		private System.Nullable<double> _F20;
		
		private System.Nullable<double> _F21;
		
		private System.Nullable<double> _F22;
		
		private System.Nullable<double> _F23;
		
		private System.Nullable<double> _F24;
		
		private System.Nullable<double> _F25;
		
		private System.Nullable<double> _F26;
		
		private System.Nullable<double> _F27;
		
		private System.Nullable<double> _F28;
		
		private System.Nullable<double> _F29;
		
		public Temp_Table_of_Player_Stat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NBA_Stats", DbType="NVarChar(255)")]
		public string NBA_Stats
		{
			get
			{
				return this._NBA_Stats;
			}
			set
			{
				if ((this._NBA_Stats != value))
				{
					this._NBA_Stats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F2", DbType="NVarChar(255)")]
		public string F2
		{
			get
			{
				return this._F2;
			}
			set
			{
				if ((this._F2 != value))
				{
					this._F2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F3", DbType="NVarChar(255)")]
		public string F3
		{
			get
			{
				return this._F3;
			}
			set
			{
				if ((this._F3 != value))
				{
					this._F3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F4", DbType="NVarChar(255)")]
		public string F4
		{
			get
			{
				return this._F4;
			}
			set
			{
				if ((this._F4 != value))
				{
					this._F4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F5", DbType="Float")]
		public System.Nullable<double> F5
		{
			get
			{
				return this._F5;
			}
			set
			{
				if ((this._F5 != value))
				{
					this._F5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F6", DbType="Float")]
		public System.Nullable<double> F6
		{
			get
			{
				return this._F6;
			}
			set
			{
				if ((this._F6 != value))
				{
					this._F6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F7", DbType="Float")]
		public System.Nullable<double> F7
		{
			get
			{
				return this._F7;
			}
			set
			{
				if ((this._F7 != value))
				{
					this._F7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F8", DbType="Float")]
		public System.Nullable<double> F8
		{
			get
			{
				return this._F8;
			}
			set
			{
				if ((this._F8 != value))
				{
					this._F8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F9", DbType="Float")]
		public System.Nullable<double> F9
		{
			get
			{
				return this._F9;
			}
			set
			{
				if ((this._F9 != value))
				{
					this._F9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F10", DbType="Float")]
		public System.Nullable<double> F10
		{
			get
			{
				return this._F10;
			}
			set
			{
				if ((this._F10 != value))
				{
					this._F10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F11", DbType="Float")]
		public System.Nullable<double> F11
		{
			get
			{
				return this._F11;
			}
			set
			{
				if ((this._F11 != value))
				{
					this._F11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F12", DbType="Float")]
		public System.Nullable<double> F12
		{
			get
			{
				return this._F12;
			}
			set
			{
				if ((this._F12 != value))
				{
					this._F12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F13", DbType="Float")]
		public System.Nullable<double> F13
		{
			get
			{
				return this._F13;
			}
			set
			{
				if ((this._F13 != value))
				{
					this._F13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F14", DbType="Float")]
		public System.Nullable<double> F14
		{
			get
			{
				return this._F14;
			}
			set
			{
				if ((this._F14 != value))
				{
					this._F14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F15", DbType="Float")]
		public System.Nullable<double> F15
		{
			get
			{
				return this._F15;
			}
			set
			{
				if ((this._F15 != value))
				{
					this._F15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F16", DbType="Float")]
		public System.Nullable<double> F16
		{
			get
			{
				return this._F16;
			}
			set
			{
				if ((this._F16 != value))
				{
					this._F16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F17", DbType="Float")]
		public System.Nullable<double> F17
		{
			get
			{
				return this._F17;
			}
			set
			{
				if ((this._F17 != value))
				{
					this._F17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F18", DbType="Float")]
		public System.Nullable<double> F18
		{
			get
			{
				return this._F18;
			}
			set
			{
				if ((this._F18 != value))
				{
					this._F18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F19", DbType="Float")]
		public System.Nullable<double> F19
		{
			get
			{
				return this._F19;
			}
			set
			{
				if ((this._F19 != value))
				{
					this._F19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F20", DbType="Float")]
		public System.Nullable<double> F20
		{
			get
			{
				return this._F20;
			}
			set
			{
				if ((this._F20 != value))
				{
					this._F20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F21", DbType="Float")]
		public System.Nullable<double> F21
		{
			get
			{
				return this._F21;
			}
			set
			{
				if ((this._F21 != value))
				{
					this._F21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F22", DbType="Float")]
		public System.Nullable<double> F22
		{
			get
			{
				return this._F22;
			}
			set
			{
				if ((this._F22 != value))
				{
					this._F22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F23", DbType="Float")]
		public System.Nullable<double> F23
		{
			get
			{
				return this._F23;
			}
			set
			{
				if ((this._F23 != value))
				{
					this._F23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F24", DbType="Float")]
		public System.Nullable<double> F24
		{
			get
			{
				return this._F24;
			}
			set
			{
				if ((this._F24 != value))
				{
					this._F24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F25", DbType="Float")]
		public System.Nullable<double> F25
		{
			get
			{
				return this._F25;
			}
			set
			{
				if ((this._F25 != value))
				{
					this._F25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F26", DbType="Float")]
		public System.Nullable<double> F26
		{
			get
			{
				return this._F26;
			}
			set
			{
				if ((this._F26 != value))
				{
					this._F26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F27", DbType="Float")]
		public System.Nullable<double> F27
		{
			get
			{
				return this._F27;
			}
			set
			{
				if ((this._F27 != value))
				{
					this._F27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F28", DbType="Float")]
		public System.Nullable<double> F28
		{
			get
			{
				return this._F28;
			}
			set
			{
				if ((this._F28 != value))
				{
					this._F28 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F29", DbType="Float")]
		public System.Nullable<double> F29
		{
			get
			{
				return this._F29;
			}
			set
			{
				if ((this._F29 != value))
				{
					this._F29 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Player_Stats")]
	public partial class Player_Stat
	{
		
		private string _PlayerName;
		
		private string _Pos;
		
		private System.Nullable<int> _Age;
		
		private string _Team;
		
		private System.Nullable<int> _G;
		
		private System.Nullable<int> _GS;
		
		private System.Nullable<double> _MP;
		
		private System.Nullable<double> _FG;
		
		private System.Nullable<double> _FGA;
		
		private System.Nullable<double> _FGP;
		
		private System.Nullable<double> _THP;
		
		private System.Nullable<double> _THPA;
		
		private System.Nullable<double> _THPP;
		
		private System.Nullable<double> _TWP;
		
		private System.Nullable<double> _TWPA;
		
		private System.Nullable<double> _TWPP;
		
		private System.Nullable<double> _eFGP;
		
		private System.Nullable<double> _FT;
		
		private System.Nullable<double> _FTA;
		
		private System.Nullable<double> _FTP;
		
		private System.Nullable<double> _ORB;
		
		private System.Nullable<double> _DRB;
		
		private System.Nullable<double> _TRB;
		
		private System.Nullable<double> _AST;
		
		private System.Nullable<double> _STL;
		
		private System.Nullable<double> _BLK;
		
		private System.Nullable<double> _TOV;
		
		private System.Nullable<double> _PF;
		
		private System.Nullable<double> _PTS;
		
		public Player_Stat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerName", DbType="Char(100)")]
		public string PlayerName
		{
			get
			{
				return this._PlayerName;
			}
			set
			{
				if ((this._PlayerName != value))
				{
					this._PlayerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos", DbType="Char(5)")]
		public string Pos
		{
			get
			{
				return this._Pos;
			}
			set
			{
				if ((this._Pos != value))
				{
					this._Pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team", DbType="Char(3)")]
		public string Team
		{
			get
			{
				return this._Team;
			}
			set
			{
				if ((this._Team != value))
				{
					this._Team = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="Int")]
		public System.Nullable<int> G
		{
			get
			{
				return this._G;
			}
			set
			{
				if ((this._G != value))
				{
					this._G = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GS", DbType="Int")]
		public System.Nullable<int> GS
		{
			get
			{
				return this._GS;
			}
			set
			{
				if ((this._GS != value))
				{
					this._GS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MP", DbType="Float")]
		public System.Nullable<double> MP
		{
			get
			{
				return this._MP;
			}
			set
			{
				if ((this._MP != value))
				{
					this._MP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FG", DbType="Float")]
		public System.Nullable<double> FG
		{
			get
			{
				return this._FG;
			}
			set
			{
				if ((this._FG != value))
				{
					this._FG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGA", DbType="Float")]
		public System.Nullable<double> FGA
		{
			get
			{
				return this._FGA;
			}
			set
			{
				if ((this._FGA != value))
				{
					this._FGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGP", DbType="Float")]
		public System.Nullable<double> FGP
		{
			get
			{
				return this._FGP;
			}
			set
			{
				if ((this._FGP != value))
				{
					this._FGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THP", DbType="Float")]
		public System.Nullable<double> THP
		{
			get
			{
				return this._THP;
			}
			set
			{
				if ((this._THP != value))
				{
					this._THP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THPA", DbType="Float")]
		public System.Nullable<double> THPA
		{
			get
			{
				return this._THPA;
			}
			set
			{
				if ((this._THPA != value))
				{
					this._THPA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THPP", DbType="Float")]
		public System.Nullable<double> THPP
		{
			get
			{
				return this._THPP;
			}
			set
			{
				if ((this._THPP != value))
				{
					this._THPP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TWP", DbType="Float")]
		public System.Nullable<double> TWP
		{
			get
			{
				return this._TWP;
			}
			set
			{
				if ((this._TWP != value))
				{
					this._TWP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TWPA", DbType="Float")]
		public System.Nullable<double> TWPA
		{
			get
			{
				return this._TWPA;
			}
			set
			{
				if ((this._TWPA != value))
				{
					this._TWPA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TWPP", DbType="Float")]
		public System.Nullable<double> TWPP
		{
			get
			{
				return this._TWPP;
			}
			set
			{
				if ((this._TWPP != value))
				{
					this._TWPP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eFGP", DbType="Float")]
		public System.Nullable<double> eFGP
		{
			get
			{
				return this._eFGP;
			}
			set
			{
				if ((this._eFGP != value))
				{
					this._eFGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FT", DbType="Float")]
		public System.Nullable<double> FT
		{
			get
			{
				return this._FT;
			}
			set
			{
				if ((this._FT != value))
				{
					this._FT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTA", DbType="Float")]
		public System.Nullable<double> FTA
		{
			get
			{
				return this._FTA;
			}
			set
			{
				if ((this._FTA != value))
				{
					this._FTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTP", DbType="Float")]
		public System.Nullable<double> FTP
		{
			get
			{
				return this._FTP;
			}
			set
			{
				if ((this._FTP != value))
				{
					this._FTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORB", DbType="Float")]
		public System.Nullable<double> ORB
		{
			get
			{
				return this._ORB;
			}
			set
			{
				if ((this._ORB != value))
				{
					this._ORB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRB", DbType="Float")]
		public System.Nullable<double> DRB
		{
			get
			{
				return this._DRB;
			}
			set
			{
				if ((this._DRB != value))
				{
					this._DRB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRB", DbType="Float")]
		public System.Nullable<double> TRB
		{
			get
			{
				return this._TRB;
			}
			set
			{
				if ((this._TRB != value))
				{
					this._TRB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AST", DbType="Float")]
		public System.Nullable<double> AST
		{
			get
			{
				return this._AST;
			}
			set
			{
				if ((this._AST != value))
				{
					this._AST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STL", DbType="Float")]
		public System.Nullable<double> STL
		{
			get
			{
				return this._STL;
			}
			set
			{
				if ((this._STL != value))
				{
					this._STL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLK", DbType="Float")]
		public System.Nullable<double> BLK
		{
			get
			{
				return this._BLK;
			}
			set
			{
				if ((this._BLK != value))
				{
					this._BLK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOV", DbType="Float")]
		public System.Nullable<double> TOV
		{
			get
			{
				return this._TOV;
			}
			set
			{
				if ((this._TOV != value))
				{
					this._TOV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PF", DbType="Float")]
		public System.Nullable<double> PF
		{
			get
			{
				return this._PF;
			}
			set
			{
				if ((this._PF != value))
				{
					this._PF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTS", DbType="Float")]
		public System.Nullable<double> PTS
		{
			get
			{
				return this._PTS;
			}
			set
			{
				if ((this._PTS != value))
				{
					this._PTS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
